# Generated by Django 2.2.6 on 2019-10-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zezere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrequest',
            name='auto_generated_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Auto generated ID'),
        ),
    ]
