# Generated by Django 2.2.6 on 2019-10-17 19:29

import django.core.validators
from django.db import migrations, models
import zezere.runreqs


class Migration(migrations.Migration):

    dependencies = [
        ('zezere', '0002_runrequest_auto_generated_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrequest',
            name='kernel_url',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[django.core.validators.URLValidator],  # type: ignore
                verbose_name='Kernel URL'
            ),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='auto_generated_id',
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True,
                unique=True,
                validators=[zezere.runreqs.validate_runreq_autoid],
                verbose_name='Auto generated ID'
            ),
        ),
    ]
