# Generated by Django 2.2.6 on 2019-10-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("zezere", "0007_auto_20191021_1444")]

    operations = [
        migrations.AddField(
            model_name="runrequest",
            name="raw_settings",
            field=models.TextField(
                blank=True, null=True, verbose_name="JSON-encoded settings"
            ),
        )
    ]
